# Generated by Django 5.2.4 on 2025-07-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='context',
            field=models.TextField(default="Noma'lum"),
            preserve_default=False,
        ),
    ]
